name: Generate template doc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install npm v8
        run: |
          npm install -g npm@8
      - name: generate doc
        run: |
          node ./_helpers/template-docs.js
      - name: check for changes
        id: changes
        run: |
          git diff --name-only | xargs
          echo "::set-output name=files::$(git diff --name-only | xargs)"
      - name: commit changes
        if: ${{ contains(steps.changes.outputs.files, 'docs/templates.md') }}
        run: |
          git config user.name twilio-labs-ci
          git config user.email 65686990+twilio-labs-ci@users.noreply.github.com
          git add docs/templates.md
          git commit -m "chore(docs): update templates doc"
          git push
